name: nebari-doctor
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  - pydantic>=2.0.0
  - pip:
    - pydantic-ai>=0.1.0
    - questionary>=1.10.0
    - rich>=13.0.0
    - typer>=0.9.0
